
package ca.on.gov.common.service.client.email;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommunicationManagementService", targetNamespace = "http://intf.comm.s2i.sodp.gov.on.ca")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommunicationManagementService {


    /**
     * 
     * @param sendCustomerEmailRequestMessage
     * @return
     *     returns ca.on.gov.common.service.client.email.VoidResponse
     * @throws SendCustomerEmailFault
     */
    @WebMethod
    @WebResult(name = "VoidResponse", targetNamespace = "http://data.s2i.sodp.gov.on.ca", partName = "SendCustomerEmailResponseMessage")
    public VoidResponse sendCustomerEmail(
        @WebParam(name = "SendCustomerEmailRequest", targetNamespace = "http://data.s2i.sodp.gov.on.ca", partName = "SendCustomerEmailRequestMessage")
        SendCustomerEmailRequest sendCustomerEmailRequestMessage)
        throws SendCustomerEmailFault
    ;

    /**
     * 
     * @param sendAnonymousEmailRequestMessage
     * @return
     *     returns ca.on.gov.common.service.client.email.VoidResponse
     * @throws SendAnonymousEmailFault
     */
    @WebMethod
    @WebResult(name = "VoidResponse", targetNamespace = "http://data.s2i.sodp.gov.on.ca", partName = "SendAnonymousEmailResponseMessage")
    public VoidResponse sendAnonymousEmail(
        @WebParam(name = "SendAnonymousEmailRequest", targetNamespace = "http://data.s2i.sodp.gov.on.ca", partName = "SendAnonymousEmailRequestMessage")
        SendAnonymousEmailRequest sendAnonymousEmailRequestMessage)
        throws SendAnonymousEmailFault
    ;

    /**
     * 
     * @param sendAsyncEmailRequestMessage
     * @return
     *     returns ca.on.gov.common.service.client.email.VoidResponse
     * @throws SendAsyncEmailSendAsyncEmailFaultMsg
     */
    @WebMethod
    @WebResult(name = "VoidResponse", targetNamespace = "http://data.s2i.sodp.gov.on.ca", partName = "SendAsyncEmailResponseMessage")
    public VoidResponse sendAsyncEmail(
        @WebParam(name = "SendAsyncEmailRequest", targetNamespace = "http://data.s2i.sodp.gov.on.ca", partName = "SendAsyncEmailRequestMessage")
        SendAsyncEmailRequest sendAsyncEmailRequestMessage)
        throws SendAsyncEmailSendAsyncEmailFaultMsg
    ;

    /**
     * 
     * @param listGeneralCommunicationEventsRequestMessage
     * @return
     *     returns ca.on.gov.common.service.client.email.ListGeneralCommunicationEventsResponse
     * @throws ListGeneralCommunicationEventsFault
     */
    @WebMethod
    @WebResult(name = "ListGeneralCommunicationEventsResponse", targetNamespace = "http://data.s2i.sodp.gov.on.ca", partName = "ListGeneralCommunicationEventsResponseMessage")
    public ListGeneralCommunicationEventsResponse listGeneralCommunicationEvents(
        @WebParam(name = "ListGeneralCommunicationEventsRequest", targetNamespace = "http://data.s2i.sodp.gov.on.ca", partName = "ListGeneralCommunicationEventsRequestMessage")
        ListGeneralCommunicationEventsRequest listGeneralCommunicationEventsRequestMessage)
        throws ListGeneralCommunicationEventsFault
    ;

    /**
     * 
     * @param putGeneralCommunicationEventRequestMessage
     * @return
     *     returns ca.on.gov.common.service.client.email.VoidResponse
     * @throws PutGeneralCommunicationEventFault
     */
    @WebMethod
    @WebResult(name = "VoidResponse", targetNamespace = "http://data.s2i.sodp.gov.on.ca", partName = "PutGeneralCommunicationEventResponseMessage")
    public VoidResponse putGeneralCommunicationEvent(
        @WebParam(name = "PutGeneralCommunicationEventRequest", targetNamespace = "http://data.s2i.sodp.gov.on.ca", partName = "PutGeneralCommunicationEventRequestMessage")
        GeneralCommunicationEventType putGeneralCommunicationEventRequestMessage)
        throws PutGeneralCommunicationEventFault
    ;

}
